[package]
name = "punter"
version = "0.1.0"
authors = ["Stephen Crane"]

[dependencies]
getopts = "0.2"
bufstream = "0.1.3"
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0.11"
rand = "0.3"
bincode = "0.8.0"
serde_bytes = "0.10.1"
